# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160125_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_complete',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
