# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160129_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(max_length=250)),
                ('festival_city', models.CharField(max_length=50)),
                ('festival_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Festival'),
            preserve_default=False,
        ),
    ]
